### ISSUE TITLE
[Orders] Add tax to earnings

### ISSUE THREAD

**Issue by PaiAkshay998** [delta/dalal-street-server#236]
For the game to adjust in terms of difficulty for relatively wealthy players, we could have tax instead of mortage interest over time. I feel this solves the issue better. We could have tax brackets based on net worth.

**Comment by thakkarparth007** [comment]
Where do you plan to add the tax?

**Comment by PaiAkshay998** [comment]
Everytime you get cash. Basically everytime a sell gets executed.

**Comment by PaiAkshay998** [comment]
We follow the four tax bracket system the Indian government follows with ofcourse the limits set different. For now, define constants to differentiate the different levels; the values of these constants can always be changed later. So these are going to be static limits and based on the net worth of the person.

A person will be charged tax on his _earnings_ that is each time he sells a stock.

**Comment by nimishagarwal76** [comment]
<h1> Proposed Solution </h1>

- Everytime a user bids a stock, for all the stocks he has for the stockId, his average cost of the stocks would be calculated from transactions table
- Average price is basically    (Total amount he lost/gained) / Amout of stocks he owns
- Now the difference in cost of stock he is purchasing to that of average price he traded stocks, will determine how much profit he gained.
- Based on profits taxes would be implemented

<h3> Note </h3> 

 - This will increase difficulty as sudden Profits would be obiliged to pay taxes accordingly

<h4> Alternative Solution </h4>

- Collect taxes on a regular interval based on whether he is at loss or profit

**Comment by PaiAkshay998** [comment]
I feel the alternative solution is the most simple to perform. What I feel is, at the end of the day, simply tax people based on net profit from ```OrderFillTransactions```. Create a new transaction called ```TaxTransaction``` for this.

Also, we cannot simply tax people out of nowhere. We need to update portfolio on frontend to show people their current profit / loss for the day and estimated tax for the day.

**Comment by PaiAkshay998** [comment]
Potential problems:
1. If I purchase worth Rs. 100 today and sell for Rs. 100 the next day, I shouldn't be taxed because I haven't made a profit. But if you the timeframe approach to tax, the purchase of Rs 100 won't be considered as it was on the previous day. You will be taxed on the Rs. 100 you made today.
2. Say I purchase stocks worth Rs. 100 today. Sell for Rs. 200. And end of day purchase stocks worth Rs. 100 again. Now, I have Rs.100 in cash and Rs. 100 in stocks but OrderFillTransaction says I made no profit when I have actually made a profit of Rs. 100

**Comment by gauthamk97** [comment]
# Overview
Tax will be applied at every time a Ask order or Buy order is executed since this is when there is a potential that the player has made a profit.

# Tax Calculation
If user buys *x* stocks at a price of *p1* and then sells those *x* stocks at a price of *p2*, then
```go
profit := (p2-p1)*x
if (profit>0) {
    tax = taxPercent * profit //taxPercent depends on which tax bracket the user falls under which is determined by Net Worth.
} else {
    tax = 0
}
```

# Implementation
1. Create new table **TransactionSummary** whose structure is 

| UserID | StockID | StockQty | Price
| ------ |:--------:| -----:| -----:|

2. Add/Update table whenever a Bid or Ask is executed
3. Charge tax in one of 2 cases 
   1. When Ask is executed, if the corresponding entry in **TransactionSummary** has a positive stock quantity.
   2. When Bid is exexuted, if the corresponding entry in **TransactionSummary** has a negative stock quantity. (This is for short selling).

# Example
1. When UserID 1 buys 5 stocks of StockID 1 at a price of 20 per stock

| UserID | StockID | StockQty | Price
| ------ |:--------:| -----:| -----:|
| 1 | 1 | 5 | 20

2. When UserID 1 buys 5 **more** stocks of StockID 1 at a price of 15 per stock

| UserID | StockID | StockQty | Price
| ------ |:--------:| -----:| -----:|
| 1 | 1 | 10 | 17.5

3. When UserID 1 sells 8 stocks of StockID 1 at a price of 19 per stock

| UserID | StockID | StockQty | Price
| ------ |:--------:| -----:| -----:|
| 1 | 1 | 2 | 17.5

**and the tax is charged**
```
profit = (19-17.5)*8 = 12
tax = taxPercent * 12
```

# Example 2 (short selling)
1. When UserID 1 short sells 10 stocks of StockID 1 at a price of 20 per stock

| UserID | StockID | StockQty | Price
| ------ |:--------:| -----:| -----:|
| 1 | 1 | -10 | 20

2. When UserID 1 buys back 8 stocks of StockID 1 at a price of 17 per stock

| UserID | StockID | StockQty | Price
| ------ |:--------:| -----:| -----:|
| 1 | 1 | -2 | 20

**and the tax is charged**
```
profit = (20-17)*8 = 24
tax = taxPercent * 24
```

**Comment by nimishagarwal76** [comment]
@gauthamk97  the above logic can be implemented using **Transactions** table also, where price would be total earned over the stock and dividing by total amount of stocks in his posession. So is there a need for another table?

- This will give total amount used for purchase and selling

> SELECT SUM(price) FROM `Transactions` WHERE userId = ? AND (type = "FromExchangeTransaction" OR type = "OrderFillTransaction") AND stockId = ?

- Dividing by this will give average price

> SELECT SUM(stockQuantity) FROM `Transactions` WHERE userId = ? AND (type = "FromExchangeTransaction" OR type = "OrderFillTransaction") AND stockId = ?

**Comment by gauthamk97** [comment]
The method you're suggesting won't give us the correct values.

## Example
Let the initial table status be

| UserID | StockID | StockQty | Price
| ------ |:--------:| -----:| -----:|
| 1 | 1 | 5 | 20

Basically, the user has bought 5 stocks at a price of 20 per stock.
Then let the following occur :- 
1. User sells 3 stocks at a price of 30 each,
2. User sells 2 **more** stocks at the same price (30 each)

Now clearly, the profit in this scenario is = 5*10 = 50. So let's see how both of our methods calculate this.

### Using my method
After step 1, table will be updated as :-

| UserID | StockID | StockQty | Price
| ------ |:--------:| -----:| -----:|
| 1 | 1 | 2 | 20

And the user's profit will be calculated as = (30-20)*(5-2) = 30

After step 2, table will be updated as :-

| UserID | StockID | StockQty | Price
| ------ |:--------:| -----:| -----:|
| 1 | 1 | 0 | 20

And the user's profit will be = (30-20)*(2-0) = 20

Therefore, total profit = 30 + 20 = 50 (which is the correct value)

### Using your method
Since we're using the **Transactions** table, initially the table status will be

| UserID | StockID | StockQty | Price | Total
| ------ |:--------:| -----:| -----:| ---:|
| 1 | 1 | 5 | 20 | 100

After step 1, profit will be calculated as

> avgStockPrice = sum(total)/sum(StockQty) = 100/5 = 20
profit = (30-avgStockPrice)*3 = (30-20)*3 = 30

and the table will be updated as :-

| UserID | StockID | StockQty | Price | Total
| ------ |:--------:| -----:| -----:| -----:|
| 1 | 1 | 5 | 20 | 100
| 1 | 1 | -3 | 30 | -90

After step 2, profit will be calculated as

> avgStockPrice = sum(total)/sum(StockQty) = (100-90)/5 = 2
profit = (30-2)*2 = 56

and the table will be updated as :-

| UserID | StockID | StockQty | Price | Total
| ------ |:--------:| -----:| -----:| -----:|
| 1 | 1 | 5 | 20 | 100
| 1 | 1 | -3 | 30 | -90
| 1 | 1 | -2 | 30 | -60

Therefore, total profit will be calculated as 30 + 56 = 86 which is way more than his actual profit of 50. As a result, the user will be taxed more than he actually should be, because we think his profit is higher than it actually is.

Furthermore, to even perform this, we would have to do an entire table scan for every single transaction that is executed, which given the number of users and number of transactions happening per second would be far too costly.

**Comment by nimishagarwal76** [comment]
> # Overview
> Tax will be applied every time a Ask order or Buy order is executed since this is when there is a potential that the player has made a profit.
> 
> # Tax Calculation
> If user buys _x_ stocks at a price of _p1_ and then sells those _x_ stocks at a price of _p2_, then
> 
> ```go
> profit := (p2-p1)*x
> if (profit>0) {
>     tax = taxPercent * profit //taxPercent depends on which tax bracket the user falls under which is determined by Net Worth.
> } else {
>     tax = 0
> }
> ```
> 
> # Implementation
> 1. Create new table **TransactionSummary** whose structure is
> 
> UserID	StockID	StockQty	Price
> **where (UserID, StockID) forms a primary key**
> 
> 1. Add/Update table whenever a Bid or Ask is executed
> 2. Charge tax in one of 2 cases
>    
>    1. When Ask is executed, if the corresponding entry in **TransactionSummary** has a positive stock quantity.
>    2. When Bid is exexuted, if the corresponding entry in **TransactionSummary** has a negative stock quantity. (This is for short selling).
> 
> # Example
> 1. When UserID 1 buys 5 stocks of StockID 1 at a price of 20 per stock
> 
> UserID	StockID	StockQty	Price
> 1	1	5	20
> 1. When UserID 1 buys 5 **more** stocks of StockID 1 at a price of 15 per stock
> 
> UserID	StockID	StockQty	Price
> 1	1	10	17.5
> 1. When UserID 1 sells 8 stocks of StockID 1 at a price of 19 per stock
> 
> UserID	StockID	StockQty	Price
> 1	1	2	17.5
> **and the tax is charged**
> 
> ```
> profit = (19-17.5)*8 = 12
> tax = taxPercent * 12
> ```
> # Example 2 (short selling)
> 1. When UserID 1 short sells 10 stocks of StockID 1 at a price of 20 per stock
> 
> UserID	StockID	StockQty	Price
> 1	1	-10	20
> 1. When UserID 1 buys back 8 stocks of StockID 1 at a price of 17 per stock
> 
> UserID	StockID	StockQty	Price
> 1	1	-2	20
> **and the tax is charged**
> 
> ```
> profit = (20-17)*8 = 24
> tax = taxPercent * 24
> ```

Is this final, should I start working upon it ? @PaiAkshay998  @thakkarparth007  @gauthamk97
